// AI Fluency Standard — A1→C2 curriculum.
//
// Structured the way Alliance Française builds CEFR courses: each level is a fixed
// "course" broken into competency units, every class anchored to a "can-do" statement,
// a teaching **framework** (method), measurable **outcomes**, and a hands-on **deliverable**
// (the portfolio-build model the Standard is graded on). Six classes per level, 36 in total.

export type Klass = {
  n: number;          // 1..6 within the level
  title: string;
  canDo: string;      // CEFR-style "I can …" objective
  framework: string;  // the teaching method / approach for the class
  outcomes: string[]; // measurable "by the end you can…" points
  topics: string[];   // 3–5 key concepts covered
  activity: string;   // the in-class, hands-on exercise
  deliverable: string;// the artifact that proves the class
  tools: string[];
};

export type Level = {
  code: string;       // A1..C2
  name: string;       // Breakthrough..Mastery
  band: string;       // Basic / Independent / Proficient User
  tag: string;        // short focus tag
  color: string;
  tint: string;
  border: string;
  focus: string;      // one-line course aim
  hours: number;      // notional contact hours (AF-style)
  classes: Klass[];
};

export const CURRICULUM: Level[] = [
  {
    code: "A1", name: "Breakthrough", band: "Basic User", tag: "grounded answers",
    color: "#3E8C61", tint: "rgba(62,140,97,0.12)", border: "rgba(62,140,97,0.34)",
    focus: "Personal productivity & grounded answers", hours: 12,
    classes: [
      { n: 1, title: "Talking to AI: prompts that work",
        canDo: "I can write clear prompts and reliably get the answer I need from a chat model.",
        framework: "Instruct → context → example → iterate",
        outcomes: ["Structure any prompt with role, context and an example", "Refine a weak answer in 2–3 iterations", "Save prompts you reuse as templates"],
        topics: ["Roles & instructions", "Giving context", "Examples", "Iterating", "Reusable templates"],
        activity: "Take five vague prompts and rewrite them until each returns a usable answer, then save the winners.",
        deliverable: "A personal library of reusable prompt templates for your common tasks.",
        tools: ["Claude", "ChatGPT", "Gemini"] },
      { n: 2, title: "Judging answers & using AI responsibly",
        canDo: "I can tell when an AI answer is trustworthy, and I know what is safe to put into AI tools.",
        framework: "Verify claims · protect data",
        outcomes: ["Spot unsupported claims and decide when to verify", "Keep secrets, PII and confidential data out of AI tools"],
        topics: ["Hallucination", "Confidence vs correctness", "Data privacy: what not to paste", "Confidentiality & approved tools"],
        activity: "Fact-check a set of AI outputs, then redraft a risky prompt so no sensitive data leaves the org.",
        deliverable: "A verification + safe-use checklist (including what must never be pasted).",
        tools: ["Claude", "ChatGPT"] },
      { n: 3, title: "Working with your own documents",
        canDo: "I can upload a document and get cited, scoped answers from it.",
        framework: "Upload → ask → quote the source",
        outcomes: ["Get scoped answers from a real document", "Attribute every fact to its source"],
        topics: ["File uploads", "Summarising", "Extracting facts", "Quoting the source"],
        activity: "Load a real report and interrogate it for the figures that matter.",
        deliverable: "A one-page, source-cited summary of a real document.",
        tools: ["Claude", "ChatGPT"] },
      { n: 4, title: "Knowledge hubs: grounding AI in company docs",
        canDo: "I can build a small knowledge base the AI answers from, so replies stay on-brand.",
        framework: "Curate → ground → constrain",
        outcomes: ["Assemble a small grounded knowledge base", "Keep answers on-source and on-brand"],
        topics: ["Knowledge bases", "Grounding", "Notion AI", "Curating sources"],
        activity: "Assemble five canonical company documents into one workspace.",
        deliverable: "A grounded FAQ assistant that answers only from your sources.",
        tools: ["Notion AI", "Claude"] },
      { n: 5, title: "Building a Custom GPT — no code",
        canDo: "I can configure and publish a simple Custom GPT for a defined task.",
        framework: "Instruct → equip → publish",
        outcomes: ["Configure a Custom GPT for one job", "Publish and share it with others"],
        topics: ["GPT Builder", "Instructions", "Knowledge files", "Publishing & sharing"],
        activity: "Configure a Custom GPT end-to-end in the builder.",
        deliverable: "A published Custom GPT scoped to one real job.",
        tools: ["ChatGPT (GPT Builder)"] },
      { n: 6, title: "Capstone — client-intake assistant",
        canDo: "I can ship a chat assistant that answers FAQs, qualifies leads, and routes enquiries.",
        framework: "Scope → build → test → ship",
        outcomes: ["Ship a working client-intake assistant", "Validate it against real questions"],
        topics: ["Scoping", "Testing", "Handoff", "Going live"],
        activity: "Build, test, and stand up the assistant on a real page.",
        deliverable: "A live Custom GPT for client intake — the A1 reference build.",
        tools: ["ChatGPT", "Claude"] },
    ],
  },
  {
    code: "A2", name: "Waystage", band: "Basic User", tag: "cited research",
    color: "#34805A", tint: "rgba(52,128,90,0.12)", border: "rgba(52,128,90,0.34)",
    focus: "Proprietary context, research & high-output work", hours: 12,
    classes: [
      { n: 1, title: "Projects & persistent context",
        canDo: "I can set up a Project that remembers my context across every chat.",
        framework: "Set context once → reuse everywhere",
        outcomes: ["Stand up a Project with standing instructions", "Keep context across separate chats"],
        topics: ["Claude Projects", "Custom instructions", "Persistent memory", "Scoping a Project"],
        activity: "Create a Project with standing instructions for a recurring task.",
        deliverable: "A configured research Project that keeps its context.",
        tools: ["Claude Projects"] },
      { n: 2, title: "Loading an internal archive",
        canDo: "I can load internal documents so every answer is grounded and cited.",
        framework: "Curate → load → verify recall",
        outcomes: ["Ground a Project in real internal archives", "Confirm it cites the right document"],
        topics: ["Knowledge files", "Archive curation", "Retrieval limits", "Source hygiene"],
        activity: "Load a body of company docs and test grounded recall.",
        deliverable: "An archive-backed Project that cites the right document.",
        tools: ["Claude Projects"] },
      { n: 3, title: "Research at scale: synthesis & deep research",
        canDo: "I can run deep-research agents and synthesise many sources into one cited brief.",
        framework: "Gather → deep-research → synthesise → cite",
        outcomes: ["Run a deep-research report and verify it", "Synthesise many sources into cited, structured output"],
        topics: ["Deep Research agents", "Multi-doc synthesis", "Comparison", "Citation"],
        activity: "Run a Deep Research report, then refine and fact-check it into a brief.",
        deliverable: "A cited research brief built from a deep-research run plus your own sources.",
        tools: ["Claude / ChatGPT / Gemini Deep Research", "Perplexity", "Claude Projects"] },
      { n: 4, title: "Multimodal output: images, voice & decks",
        canDo: "I can generate professional images, voiceovers and slide decks with AI.",
        framework: "Brief → generate → refine",
        outcomes: ["Generate on-brand images and a voiceover", "Turn a document into a polished deck"],
        topics: ["Image generation", "Text-to-speech / voice", "AI slide decks", "Brand & licensing"],
        activity: "Produce an image set, a short voiceover, and a deck for one real piece of work.",
        deliverable: "A multimodal asset pack (images + voice + deck) for a real project.",
        tools: ["Midjourney", "DALL·E", "ElevenLabs", "Gamma"] },
      { n: 5, title: "Citations you can trust",
        canDo: "I can make outputs verifiable with inline citations and reduce drift.",
        framework: "Draft → cite → verify",
        outcomes: ["Add verifiable inline citations", "Reduce drift with source-checking"],
        topics: ["Citation discipline", "Source-checking", "Reducing drift", "Review"],
        activity: "Add inline citations to a draft and verify each one.",
        deliverable: "A citation-verified report ready to circulate.",
        tools: ["Claude Projects"] },
      { n: 6, title: "Capstone — a team research Project",
        canDo: "I can deliver a Project the whole team queries for cited answers on demand.",
        framework: "Build → document → hand off",
        outcomes: ["Deliver a shared team research Project", "Equip the team to run it themselves"],
        topics: ["Rollout", "Instructions", "Maintenance", "Handoff"],
        activity: "Build and hand off the Project with usage guidance.",
        deliverable: "A team Claude Project loaded with internal archives — the A2 reference build.",
        tools: ["Claude Projects", "Custom GPTs"] },
    ],
  },
  {
    code: "B1", name: "Threshold", band: "Independent User", tag: "automation",
    color: "#2C7350", tint: "rgba(44,115,80,0.12)", border: "rgba(44,115,80,0.34)",
    focus: "Workflow automation with AI in the loop", hours: 14,
    classes: [
      { n: 1, title: "Mapping a manual workflow",
        canDo: "I can break a manual process into automatable steps.",
        framework: "Trigger → steps → inputs/outputs",
        outcomes: ["Map a process into automatable steps", "Identify the trigger and data flow"],
        topics: ["Process mapping", "Triggers", "Steps", "Inputs & outputs"],
        activity: "Diagram a real recurring task as a step-by-step flow.",
        deliverable: "A workflow map ready to automate.",
        tools: ["Gumloop", "Zapier"] },
      { n: 2, title: "Connecting tools: triggers & actions",
        canDo: "I can connect apps so an event in one triggers an action in another.",
        framework: "Trigger → action → pass data",
        outcomes: ["Connect two apps event-to-action", "Pass data cleanly between steps"],
        topics: ["Triggers", "Actions", "Authentication", "Passing data"],
        activity: "Build a two-step automation between two apps.",
        deliverable: "A working trigger → action automation.",
        tools: ["Zapier", "Make"] },
      { n: 3, title: "AI in the loop",
        canDo: "I can insert an AI step that enriches, classifies, or decides inside a workflow.",
        framework: "Ingest → AI step → route",
        outcomes: ["Insert an AI enrichment/decision step", "Route records on the AI's output"],
        topics: ["AI steps", "Enrichment", "Classification", "Prompts in automation"],
        activity: "Add a Claude step that enriches each record as it passes through.",
        deliverable: "An AI-enriched automation.",
        tools: ["Zapier", "n8n", "Claude"] },
      { n: 4, title: "Data handling, privacy & error paths",
        canDo: "I can handle messy data and failures safely, without leaking sensitive data.",
        framework: "Validate → format → retry → branch",
        outcomes: ["Handle messy data with retries and error branches", "Keep PII out of logs and AI steps"],
        topics: ["Data mapping", "Formatting", "PII & data privacy", "Retries & error branches"],
        activity: "Add formatting, error branches, and PII redaction to a fragile workflow.",
        deliverable: "A fault-tolerant, privacy-safe workflow.",
        tools: ["n8n", "Make"] },
      { n: 5, title: "Scheduling & monitoring",
        canDo: "I can schedule runs and monitor them in production.",
        framework: "Schedule → log → alert",
        outcomes: ["Run a workflow on a schedule", "Get alerted the moment it fails"],
        topics: ["Schedules", "Logs", "Alerts", "Observability basics"],
        activity: "Schedule a workflow and wire failure alerts.",
        deliverable: "A monitored, scheduled automation.",
        tools: ["n8n", "Zapier"] },
      { n: 6, title: "Capstone — end-to-end onboarding automation",
        canDo: "I can ship a multi-step automation that runs daily with no manual touch.",
        framework: "Wire → test → go live",
        outcomes: ["Ship a daily end-to-end automation", "Run it with zero manual touch"],
        topics: ["Integration", "Testing", "Handoff", "Go-live"],
        activity: "Build the full pipeline wiring CRM, Gmail, and an AI step.",
        deliverable: "A client-onboarding automation that runs end-to-end — the B1 reference build.",
        tools: ["Gumloop", "Zapier", "n8n", "Make"] },
    ],
  },
  {
    code: "B2", name: "Vantage", band: "Independent User", tag: "agents & tools",
    color: "#236444", tint: "rgba(35,100,68,0.12)", border: "rgba(35,100,68,0.34)",
    focus: "Scripted agents & retrieval-grounded tooling", hours: 16,
    classes: [
      { n: 1, title: "From chat to product",
        canDo: "I can frame an AI capability as a shippable tool, not just a chat.",
        framework: "User → job → interface",
        outcomes: ["Frame a capability as a real tool", "Write a tight one-page spec"],
        topics: ["Product framing", "Scope", "Users", "Interfaces"],
        activity: "Write a tight spec for a tool a non-technical user could run.",
        deliverable: "A one-page tool spec.",
        tools: ["Cursor", "Claude Code"] },
      { n: 2, title: "Retrieval foundations (RAG)",
        canDo: "I can ground a model in private data with retrieval.",
        framework: "Chunk → embed → retrieve → cite",
        outcomes: ["Build a retrieval index over private data", "Return grounded, cited answers"],
        topics: ["Embeddings", "Vector search", "Chunking", "Retrieval"],
        activity: "Build a retrieval index over a private document set.",
        deliverable: "A cited Q&A tool over private docs.",
        tools: ["Supabase", "Claude Code"] },
      { n: 3, title: "Tool-calling agents & MCP",
        canDo: "I can give a model tools it can call — via function calling and MCP — to take real actions.",
        framework: "Define tools → call → act",
        outcomes: ["Wire callable tools with function calling", "Connect an agent to tools via an MCP server"],
        topics: ["Function calling & schemas", "MCP servers", "Runtime tool discovery", "Structured output"],
        activity: "Give an agent two tools — one via function calling, one via an MCP server.",
        deliverable: "A tool-calling agent (function calling + MCP) that acts, not just answers.",
        tools: ["Claude Code", "MCP", "Cursor"] },
      { n: 4, title: "Vibe-coding: build apps with AI",
        canDo: "I can build and ship a working app fast — from a prompt or in an AI editor.",
        framework: "Scaffold → iterate → ship",
        outcomes: ["Ship an app from a prompt with an app builder", "Build & deploy with an AI coding assistant"],
        topics: ["App builders (prompt-to-app)", "AI editors", "Debugging with AI", "Deploy"],
        activity: "Build one app with an app builder (v0 / Lovable) and refine one in Cursor / Claude Code.",
        deliverable: "A deployed mini-app.",
        tools: ["v0", "Lovable", "Cursor", "Claude Code", "Replit"] },
      { n: 5, title: "Data + dashboards",
        canDo: "I can ship a data product with a real database behind it.",
        framework: "Schema → query → UI",
        outcomes: ["Design a schema and queries", "Ship a live data dashboard"],
        topics: ["Schema design", "Queries", "Supabase", "UI"],
        activity: "Build a dashboard backed by a live database.",
        deliverable: "A live data dashboard.",
        tools: ["Supabase", "Cursor"] },
      { n: 6, title: "Capstone — a retrieval-grounded data product",
        canDo: "I can ship a working product with an integrated AI analyst.",
        framework: "Build → embed analyst → deploy",
        outcomes: ["Ship a product with an embedded AI analyst", "Deploy it end-to-end"],
        topics: ["Integration", "Deployment", "Evaluation", "Polish"],
        activity: "Build and deploy a data product with an embedded analyst.",
        deliverable: "A macro-intelligence dashboard with a Claude analyst — the B2 reference build.",
        tools: ["Cursor", "Claude Code", "Supabase"] },
    ],
  },
  {
    code: "C1", name: "Advanced", band: "Proficient User", tag: "production",
    color: "#1A5638", tint: "rgba(26,86,56,0.12)", border: "rgba(26,86,56,0.34)",
    focus: "Production AI with observability & evals", hours: 16,
    classes: [
      { n: 1, title: "Productionising AI features",
        canDo: "I can take an AI feature from prototype to production.",
        framework: "Prototype → harden → deploy",
        outcomes: ["Take a feature to production", "Make it reliable under real load"],
        topics: ["Reliability", "Latency", "Deployment", "Environments"],
        activity: "Harden a prototype into a deployable feature.",
        deliverable: "A production-ready AI feature.",
        tools: ["OpenRouter", "Helicone"] },
      { n: 2, title: "Observability & logging",
        canDo: "I can see exactly what my AI is doing in production.",
        framework: "Trace → log → dashboard",
        outcomes: ["Instrument every AI call", "See behaviour live in production"],
        topics: ["Tracing", "Logging", "Dashboards", "Helicone"],
        activity: "Instrument an app so every call is traced.",
        deliverable: "An observability dashboard for your AI calls.",
        tools: ["Helicone", "OpenRouter"] },
      { n: 3, title: "Evals: measuring quality",
        canDo: "I can build eval suites that catch regressions before users do.",
        framework: "Dataset → score → gate in CI",
        outcomes: ["Build an automated eval suite", "Catch regressions before release"],
        topics: ["Eval datasets", "Scoring", "Braintrust", "CI"],
        activity: "Build an eval suite for a real task and run it in CI.",
        deliverable: "An automated eval suite.",
        tools: ["Braintrust"] },
      { n: 4, title: "Cost & token management",
        canDo: "I can manage token cost and route across models sensibly.",
        framework: "Measure → route → cache",
        outcomes: ["Cut the cost of a workload", "Route models by need without losing quality"],
        topics: ["Token budgets", "Model routing", "Caching", "Model selection"],
        activity: "Cut the cost of a workload without losing quality.",
        deliverable: "A cost-managed routing setup.",
        tools: ["OpenRouter", "Helicone"] },
      { n: 5, title: "Human-in-the-loop, governance & escalation",
        canDo: "I can design safe escalation paths and apply governance so AI stays within policy.",
        framework: "Score → threshold → escalate",
        outcomes: ["Add a confidence-based escalation path with a human in control", "Apply an acceptable-use policy and guardrails"],
        topics: ["Confidence thresholds", "Guardrails & acceptable-use policy", "Governance & oversight", "Review queues"],
        activity: "Add a low-confidence escalation path plus a guardrail that enforces an acceptable-use rule.",
        deliverable: "An agent with a human-escalation path and a governance guardrail.",
        tools: ["Helicone", "Braintrust"] },
      { n: 6, title: "Capstone — a monitored daily agent",
        canDo: "I can ship and maintain a daily AI agent in production, not just launch it.",
        framework: "Ship → monitor → maintain",
        outcomes: ["Run a monitored daily agent", "Maintain it in production over time"],
        topics: ["Scheduling", "Monitoring", "Maintenance", "Alerting"],
        activity: "Build, deploy, and monitor a daily agent.",
        deliverable: "A retrieval-grounded daily-briefing agent, monitored in production — the C1 reference build.",
        tools: ["Helicone", "Braintrust", "OpenRouter"] },
    ],
  },
  {
    code: "C2", name: "Mastery", band: "Proficient User", tag: "autonomous agents",
    color: "#123D27", tint: "rgba(18,61,39,0.12)", border: "rgba(18,61,39,0.34)",
    focus: "Autonomous multi-agent orchestration", hours: 18,
    classes: [
      { n: 1, title: "Multi-agent architectures",
        canDo: "I can design systems where multiple agents collaborate on a goal.",
        framework: "Roles → hand-offs → orchestration",
        outcomes: ["Design a collaborating-agent system", "Define clear roles and hand-offs"],
        topics: ["Orchestration", "Agent roles", "Hand-offs", "LangGraph / CrewAI"],
        activity: "Design an agent graph for a multi-step goal.",
        deliverable: "A multi-agent architecture diagram.",
        tools: ["LangGraph", "CrewAI"] },
      { n: 2, title: "Orchestration frameworks",
        canDo: "I can build an orchestrated, stateful agent workflow.",
        framework: "Graph → state → control flow",
        outcomes: ["Build a stateful agent graph", "Coordinate multiple agents reliably"],
        topics: ["Graphs", "State", "Control flow", "LangGraph"],
        activity: "Build a three-agent orchestration with shared state.",
        deliverable: "A working orchestration.",
        tools: ["LangGraph", "CrewAI"] },
      { n: 3, title: "Connecting agents via MCP",
        canDo: "I can let agents act across external accounts and APIs safely, using MCP as the standard connector.",
        framework: "Discover → call → guard",
        outcomes: ["Connect agents to systems through MCP servers", "Add guardrails on every external action"],
        topics: ["MCP servers", "Runtime tool discovery", "OAuth & auth", "Action guardrails"],
        activity: "Connect an agent to two systems via MCP servers.",
        deliverable: "An agent that acts across systems through MCP.",
        tools: ["MCP", "LangGraph"] },
      { n: 4, title: "Autonomous decision-making",
        canDo: "I can build agents that decide and act without manual triggers.",
        framework: "Plan → select tool → act",
        outcomes: ["Build an autonomous plan-act loop", "Act without manual triggers"],
        topics: ["Autonomy", "Planning", "Tool selection", "Guardrails"],
        activity: "Build an autonomous loop that plans and acts.",
        deliverable: "An autonomous decision agent.",
        tools: ["OpenAI Agents SDK", "CrewAI"] },
      { n: 5, title: "Safety, governance & oversight at scale",
        canDo: "I can keep autonomous systems safe, auditable, governed, and controllable.",
        framework: "Guardrail → audit → kill-switch",
        outcomes: ["Make autonomy auditable with controls and a kill-switch", "Enforce org AI governance and policy"],
        topics: ["Guardrails & kill switches", "Audit logs", "AI governance & policy", "Oversight"],
        activity: "Add controls, an audit trail, and a policy guardrail to an autonomous system.",
        deliverable: "A governed autonomous system.",
        tools: ["LangGraph", "Helicone"] },
      { n: 6, title: "Capstone — a business-running agent",
        canDo: "I can ship an autonomous agent that runs a business function end-to-end.",
        framework: "Integrate → automate → oversee",
        outcomes: ["Ship an agent that runs a business function", "Surface decisions and act on them"],
        topics: ["Integration", "Autonomy", "Monitoring", "Handoff"],
        activity: "Build and deploy an agent that links accounts and surfaces decisions.",
        deliverable: "A business-management agent that gathers signals and acts — the C2 reference build.",
        tools: ["LangGraph", "CrewAI", "OpenAI Agents SDK"] },
    ],
  },
];

// Helper: look up a level by its code (A1..C2), case-insensitive.
export function levelByCode(code: string): Level | undefined {
  return CURRICULUM.find((l) => l.code.toLowerCase() === code.toLowerCase());
}

export const TOTAL_CLASSES = CURRICULUM.reduce((n, l) => n + l.classes.length, 0); // 36
